# Generated by Django 4.1.2 on 2023-01-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Modelo do Carro', max_length=30, verbose_name='Modelo')),
                ('placa', models.CharField(help_text='Placa do Carro', max_length=12, verbose_name='Placa')),
                ('cor', models.CharField(help_text='Cor do Carro', max_length=15, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
            },
        ),
    ]
