# Generated by Django 4.1.2 on 2023-01-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['modelo'], 'verbose_name': 'Veiculo', 'verbose_name_plural': 'Veiculos'},
        ),
    ]
