# Generated by Django 4.1.2 on 2023-01-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0002_alter_funcionario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TimeField(help_text='Hora de Entrada', verbose_name='Entrada')),
                ('saida', models.TimeField(help_text='Hora de Saída', verbose_name='Saída')),
                ('data_pagamento', models.DateField(help_text='Data de Pagamento', verbose_name='Data de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da Estada', max_digits=5, verbose_name='Valor')),
                ('funcionario', models.ForeignKey(help_text='Nome do Funcionário', on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario', verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Estada',
                'verbose_name_plural': 'Estadas',
            },
        ),
    ]
