# Generated by Django 4.1.2 on 2023-01-25 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0003_veiculo_cliente'),
        ('estada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estada',
            name='veiculo',
            field=models.ForeignKey(default=1, help_text='Nome do Veiculo', on_delete=django.db.models.deletion.CASCADE, to='veiculo.veiculo', verbose_name='Veiculo'),
            preserve_default=False,
        ),
    ]
