# Generated by Django 4.1.2 on 2023-01-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, help_text='Cpf Completo', max_length=25, null=True, verbose_name='Cpf'),
        ),
    ]
