# Generated by Django 4.1.2 on 2023-01-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Cnpj', max_length=25, null=True, verbose_name='Cnpj'),
        ),
    ]
